from .user import UserSerializer, UserReadSerializer
from .productos import ProductoSerializer, ProductoRegistroSerializer
from .cotizaciones import CotizacionReadSerializer, CotizacionRegistroSerializer
from .historialProducto import historialProductoSerializer, historialProductoRegistroSerializer